name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master
      - main

env:
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  CLOUD_RUN_REGION: us-east1
  REPO_NAME: wz-bot-api
  SSO_TOKEN: ${{ secrets.SSO_TOKEN }}

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # This step is where our service account will be authenticated
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - run: |-
        gcloud --quiet auth configure-docker

    - name: Build and tag image
      run: |-
        docker build . --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"

    - name: Push image to GCR
      run: |-
        docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA

    - name: Deploy
      run: |-
        gcloud run deploy $REPO_NAME --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --project $CLOUD_RUN_PROJECT_ID \
          --region $CLOUD_RUN_REGION \
          --set-env-vars SSO_TOKEN=$SSO_TOKEN \
          --allow-unauthenticated \
          --no-use-http2 \
          --cpu 1 \
          --memory "256Mi" \
          --port 3000 \
          --quiet